
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvjuhnsbygzhkleuleit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2anVobnNieWd6aGtsZXVsZWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzI5NTIsImV4cCI6MjA2MzE0ODk1Mn0.qiY1skX3KMmhSw287Y4Z9AEXfqPkfYCKpjkbsZQmz1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
